### ISSUE TITLE
上传失败

### ISSUE THREAD

**Issue by vicky1221** [srv7/upload_dsym_to_bugly#1]
当我上传的时候 一直报错：
curl: (26) couldn't open file 

不知道作者知不知道是什么原因

**Comment by srv7** [comment]
@vicky1221  嗨， 你好。我收到了你的邮件。能否贴一下你是如何使用的？
> bundler: failed to load command: fastlane (/usr/local/bin/fastlane)

这里提示的是没有在你的电脑中找到 `fastlane`, 请确认是否安装了
