### ISSUE TITLE
现在还能用这个插件嘛，多次尝试未果

### ISSUE THREAD

**Issue by hunter858** [srv7/upload_dsym_to_bugly#12]

**Comment by srv7** [comment]
![WX20230724-114131@2x](https://github.com/srv7/upload_dsym_to_bugly/assets/15240872/81586331-a772-4128-a782-18deccdcdfa7)
这个是我的写法，参考对比一下呢。还是不行的话，把你的用法和报错消息贴一下

**Comment by hunter858** [comment]
终于在多次试错之后成功 了
upload_dsym_to_bugly(
          file_path: "#{output_dysm_name}",
          app_key: "#{buglyAppkey}",
          app_id: "#{buglyAppId}",
          bundle_id: "#{app_identifier}",
          version: get_version_number( xcodeproj: xcodeproj,target: target),
          raise_if_error: false
        )
        
        建议博主，添加 build_number ,build号，增加扩展能力，精确 某个版本的build 号

**Comment by hunter858** [comment]
后来我尝试成功了，这个插件可用，但是buildNumber 不支持，作者能否支持一下，加个参数


该邮件从移动设备发送


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "srv7/upload_dsym_to_bugly"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月24日(星期一) 中午11:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [srv7/upload_dsym_to_bugly] 现在还能用这个插件嘛，多次尝试未果 (Issue #12)





 

 这个是我的写法，参考对比一下呢。还是不行的话，把你的用法和报错消息贴一下
