### ISSUE TITLE
支持buildNumber 吗？

### ISSUE THREAD

**Issue by hunter858** [srv7/upload_dsym_to_bugly#14]
支持buildNumber 吗/， 如果BugLy 已经上传了一个1.0 build号 1的版本，重新提交了一个1.0 版本build 号2 的版本，那bugly上不会显示build 号为2 的 DSYM记录，这种怎么处理

**Comment by srv7** [comment]
这种不需要额外处理，在 bugly 的符号表管理中也只是显示版本号，没有展示 build number，crash 是通过 UUID 匹配符号表进行解析的，只要保证符号表成功上传就可以了。

**Comment by hunter858** [comment]
但是如果我一个version 可能有多次build Number的提交，我发现，bugly上，后续DSYM就没有提交了，加一下对你来说不是很简单嘛




该邮件从移动设备发送


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "srv7/upload_dsym_to_bugly"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月30日(星期二) 上午10:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [srv7/upload_dsym_to_bugly] 支持buildNumber 吗？ (Issue #14)





 
这种不需要额外处理，在 bugly 的符号表管理中也只是显示版本号，没有展示 build number，crash 是通过 UUID 匹配符号表进行解析的，只要保证符号表成功上传就可以了。

**Comment by srv7** [comment]
<img width="1209" alt="image" src="https://github.com/srv7/upload_dsym_to_bugly/assets/15240872/45622c89-df5c-4689-a466-0d9214d6052d">
一个版本号下相同的 build 号的符号表可以多次上传，可能由于bugly 的原因没有展示出来，实测 crash 也可惜正常解析，只要保证符号表正常上传就行了。可以通过 Actions.lane_context[SharedValues::UPLOAD_DSYM_TO_BUGLY_RESULT] 这个环境变量拿到上传结果。

在 bugly 的符号表上传工具中 buildNo 参数也只是针对 Android 的
<img width="983" alt="image" src="https://github.com/srv7/upload_dsym_to_bugly/assets/15240872/2204702b-b8da-43c3-9e05-f97123453731">
