### ISSUE TITLE
上传dsym出现报错

### ISSUE THREAD

**Issue by jonathanlu98** [srv7/upload_dsym_to_bugly#6]
{"rtcode"=>50500, "msg"=>"Success", "data"=>{"reponseCode"=>"-1", "reponseDesc"=>"system error"}}

配置为
	desc "Upload DSYM File To Bugly"
  lane :upload_dsym do
    upload_dsym_to_bugly(
      file_path: "./xxxx.app.dSYM.zip",
      file_name: "xxxx.app.dSYM.zip",
      app_key: "xxxx",
      app_id:"xxxx",
      api_version: 1,
      symbol_type: 2, # iOS => 2, Android => 1
      bundle_id: "xxxx",
      product_version: get_version_number()
    )
	end

**Comment by jonathanlu98** [comment]
之前上传都没有问题呢
就最近bugly强制用工具后就这样了

**Comment by srv7** [comment]
> 之前上传都没有问题呢
> 就最近bugly强制用工具后就这样了

bugly 已不再支持使用 openApi 的方式上传符号表，强制使用其上传工具进行上传。
2.0.0 版本进行了适配，请升级插件

```sh
bundle update fastlane-plugin-upload_dsym_to_bugly
```

**Comment by jonathanlu98** [comment]
感谢
