### ISSUE TITLE
file_path有的字符不能兼容, 会直接报错

### ISSUE THREAD

**Issue by hubin97** [srv7/upload_dsym_to_bugly#7]
file_path: "<path/x.app.dSYM.zip", 
此处path开始我设置成  xxx(build1), 执行插件报错
后面改成xxx_build1 又好了; 
就是输出的文件夹名称 可以 ABC_build1,但是 ABC(build1)不行;  有点诡异
![](https://tva1.sinaimg.cn/large/008i3skNgy1gsjsa480whj31co06u0ur.jpg)

**Comment by srv7** [comment]
嗨，我发布了 v2.0.1 版本修复了此问题，希望可以解决你的问题。

**Comment by hubin97** [comment]
试了下, 可以
