### ISSUE TITLE
[!] invalid byte sequence in UTF-8 (ArgumentError)

### ISSUE THREAD

**Issue by zzzzzyijie** [srv7/upload_dsym_to_bugly#8]
执行的时候，fastlane 报了这个错

https://github.com/fastlane/fastlane/issues/18723

+------------------+---------------+
|           Lane Context           |
+------------------+---------------+
| DEFAULT_PLATFORM | ios           |
| PLATFORM_NAME    | ios           |
| LANE_NAME        | ios bugupload |
+------------------+---------------+
[23:21:19]: invalid byte sequence in UTF-8

[23:21:19]: fastlane finished with errors

...

1: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.166.0/fastlane_core/lib/fastlane_core/ui/implementations/shell.rb:72:in `command_output'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.166.0/fastlane_core/lib/fastlane_core/ui/implementations/shell.rb:72:in `split': [!] invalid byte sequence in UTF-8 (ArgumentError)

**Comment by srv7** [comment]
能提供更多信息吗？从上面的描述里我得不到有用的信息，可以提供你的调用吗？比如
```rb
lane :upload_dysm do
    upload_dsym_to_bugly(
      file_path: "<path/to/your/x.app.dSYM.zip",
      app_key: "<your app_key>",
      app_id:"<your app_id>",
      bundle_id: '<your bundle id>',
      version: get_version_number,
      raise_if_error: false
    )
end
```

**Comment by zzzzzyijie** [comment]
> 能提供更多信息吗？从上面的描述里我得不到有用的信息，可以提供你的调用吗？比如
> 
> ```ruby
> lane :upload_dysm do
>     upload_dsym_to_bugly(
>       file_path: "<path/to/your/x.app.dSYM.zip",
>       app_key: "<your app_key>",
>       app_id:"<your app_id>",
>       bundle_id: '<your bundle id>',
>       version: get_version_number,
>       raise_if_error: false
>     )
> end
> ```

lane是没问题的，就按着demo填写参数..可能是中文转码问题?

**Comment by srv7** [comment]
我测试了包含中文的情况，成功上传没有出现上面的错误。请检查是不是环境出了问题。

**Comment by zzzzzyijie** [comment]
> 我测试了包含中文的情况，成功上传没有出现上面的错误。请检查是不是环境出了问题。

想问一下，执行上传后，会在我的项目里出现bugly 的文件，而我不想这些文件放在项目这里，有什么办法吗？
![image](https://user-images.githubusercontent.com/17098514/150460047-c9bcc0ff-979d-4465-b7b3-edeb71593351.png)

**Comment by srv7** [comment]
这些文件是 bugly 的工作生成的文件，目前上传完符号表之后没有清理这些文件。建议将这些文件添加到 .gitignore 文件中，或者在 CI 中才执行上传符号表。
当然如果后面还有类似的反馈，可以在工具内部上传完符号表之后清理这些文件。
